2022-01-19 17:11:36,341 INFO    MainThread:27264 [wandb_setup.py:_flush():71] setting env: {}
2022-01-19 17:11:36,341 INFO    MainThread:27264 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-19 17:11:36,341 INFO    MainThread:27264 [wandb_init.py:_log_setup():371] Logging user logs to C:\Users\acb6595\Documents\Research\places2\project_portable\code\src\d00_utils\wandb\run-20220119_171136-1708a7qh\logs\debug.log
2022-01-19 17:11:36,341 INFO    MainThread:27264 [wandb_init.py:_log_setup():372] Logging internal logs to C:\Users\acb6595\Documents\Research\places2\project_portable\code\src\d00_utils\wandb\run-20220119_171136-1708a7qh\logs\debug-internal.log
2022-01-19 17:11:36,341 INFO    MainThread:27264 [wandb_init.py:init():404] calling init triggers
2022-01-19 17:11:36,351 INFO    MainThread:27264 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-19 17:11:36,351 INFO    MainThread:27264 [wandb_init.py:init():449] starting backend
2022-01-19 17:11:36,351 INFO    MainThread:27264 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn, using: spawn
2022-01-19 17:11:36,357 INFO    MainThread:27264 [backend.py:ensure_launched():199] starting backend process...
2022-01-19 17:11:36,672 INFO    MainThread:27264 [backend.py:ensure_launched():204] started backend process with pid: 15616
2022-01-19 17:11:36,673 INFO    MainThread:27264 [wandb_init.py:init():458] backend started and connected
2022-01-19 17:11:36,673 INFO    MainThread:27264 [wandb_init.py:init():519] updated telemetry
2022-01-19 17:11:36,680 INFO    MainThread:27264 [wandb_init.py:init():549] communicating current version
2022-01-19 17:11:38,061 INFO    MainThread:27264 [wandb_init.py:init():554] got version response upgrade_message: "wandb version 0.12.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-01-19 17:11:38,061 INFO    MainThread:27264 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2022-01-19 17:11:38,328 INFO    MainThread:27264 [wandb_init.py:init():592] starting run threads in backend
2022-01-19 17:11:39,269 INFO    MainThread:27264 [wandb_run.py:_console_start():1816] atexit reg
2022-01-19 17:11:39,270 INFO    MainThread:27264 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.WRAP
2022-01-19 17:11:39,270 INFO    MainThread:27264 [wandb_run.py:_redirect():1727] Wrapping output streams.
2022-01-19 17:11:39,271 INFO    MainThread:27264 [wandb_run.py:_redirect():1751] Redirects installed.
2022-01-19 17:11:39,271 INFO    MainThread:27264 [wandb_init.py:init():619] run started, returning control to user process
2022-01-19 17:11:40,504 INFO    MainThread:27264 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 0
2022-01-19 17:11:40,505 INFO    MainThread:27264 [wandb_run.py:_restore():1758] restore
2022-01-19 17:11:41,286 INFO    MainThread:27264 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 636
  total_bytes: 636
}

2022-01-19 17:11:41,854 INFO    MainThread:27264 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 636
  total_bytes: 636
}

2022-01-19 17:11:42,049 INFO    MainThread:27264 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 636
  total_bytes: 636
}

2022-01-19 17:11:42,341 INFO    MainThread:27264 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 636
  total_bytes: 4296
}

2022-01-19 17:11:42,443 INFO    MainThread:27264 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 636
  total_bytes: 4296
}

2022-01-19 17:11:42,550 INFO    MainThread:27264 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 636
  total_bytes: 4296
}

2022-01-19 17:11:42,652 INFO    MainThread:27264 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 636
  total_bytes: 4296
}

2022-01-19 17:11:42,754 INFO    MainThread:27264 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4296
  total_bytes: 4296
}

2022-01-19 17:11:42,855 INFO    MainThread:27264 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4296
  total_bytes: 4296
}

2022-01-19 17:11:42,957 INFO    MainThread:27264 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4296
  total_bytes: 4296
}

2022-01-19 17:11:43,059 INFO    MainThread:27264 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4296
  total_bytes: 4296
}

2022-01-19 17:11:43,385 INFO    MainThread:27264 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4296
  total_bytes: 4296
}

2022-01-19 17:11:43,838 INFO    MainThread:27264 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4296
  total_bytes: 4296
}
local_info {
}

2022-01-19 17:11:44,964 INFO    MainThread:27264 [wandb_run.py:_append_files():2184] logging synced files
