2022-01-19 15:52:26,292 INFO    MainThread:31928 [wandb_setup.py:_flush():71] setting env: {}
2022-01-19 15:52:26,292 INFO    MainThread:31928 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-19 15:52:26,292 INFO    MainThread:31928 [wandb_init.py:_log_setup():371] Logging user logs to C:\Users\acb6595\Documents\Research\places2\project_portable\code\src\d01_pre_processing\wandb\run-20220119_155226-ru0bqedr\logs\debug.log
2022-01-19 15:52:26,292 INFO    MainThread:31928 [wandb_init.py:_log_setup():372] Logging internal logs to C:\Users\acb6595\Documents\Research\places2\project_portable\code\src\d01_pre_processing\wandb\run-20220119_155226-ru0bqedr\logs\debug-internal.log
2022-01-19 15:52:26,293 INFO    MainThread:31928 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000234460176A0>
2022-01-19 15:52:26,293 INFO    MainThread:31928 [wandb_init.py:init():404] calling init triggers
2022-01-19 15:52:26,293 INFO    MainThread:31928 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-19 15:52:26,293 INFO    MainThread:31928 [wandb_init.py:init():449] starting backend
2022-01-19 15:52:26,293 INFO    MainThread:31928 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn, using: spawn
2022-01-19 15:52:26,301 INFO    MainThread:31928 [backend.py:ensure_launched():199] starting backend process...
2022-01-19 15:52:26,618 INFO    MainThread:31928 [backend.py:ensure_launched():204] started backend process with pid: 7520
2022-01-19 15:52:26,619 INFO    MainThread:31928 [wandb_init.py:init():458] backend started and connected
2022-01-19 15:52:26,624 INFO    MainThread:31928 [wandb_run.py:_label_probe_notebook():917] probe notebook
2022-01-19 15:52:26,625 INFO    MainThread:31928 [wandb_run.py:_label_probe_notebook():927] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-01-19 15:52:26,625 INFO    MainThread:31928 [wandb_init.py:init():519] updated telemetry
2022-01-19 15:52:26,632 INFO    MainThread:31928 [wandb_init.py:init():549] communicating current version
2022-01-19 15:52:27,976 INFO    MainThread:31928 [wandb_init.py:init():554] got version response upgrade_message: "wandb version 0.12.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-01-19 15:52:27,976 INFO    MainThread:31928 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2022-01-19 15:52:28,201 INFO    MainThread:31928 [wandb_init.py:init():592] starting run threads in backend
2022-01-19 15:52:29,151 INFO    MainThread:31928 [wandb_run.py:_console_start():1816] atexit reg
2022-01-19 15:52:29,152 INFO    MainThread:31928 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.WRAP
2022-01-19 15:52:29,152 INFO    MainThread:31928 [wandb_run.py:_redirect():1727] Wrapping output streams.
2022-01-19 15:52:29,153 INFO    MainThread:31928 [wandb_run.py:_redirect():1751] Redirects installed.
2022-01-19 15:52:29,153 INFO    MainThread:31928 [wandb_init.py:init():619] run started, returning control to user process
2022-01-19 15:52:31,766 INFO    MainThread:31928 [wandb_run.py:finish():1463] finishing run austinbergstrom/places_dry_run/ru0bqedr
2022-01-19 15:52:31,877 INFO    MainThread:31928 [jupyter.py:save_history():429] not saving jupyter history
2022-01-19 15:52:31,877 INFO    MainThread:31928 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-19 15:52:31,877 INFO    MainThread:31928 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-01-19 15:52:31,877 INFO    MainThread:31928 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2022-01-19 15:52:31,877 INFO    MainThread:31928 [wandb_run.py:_restore():1758] restore
2022-01-19 15:52:32,242 INFO    MainThread:31928 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 649
  total_bytes: 649
}

2022-01-19 15:52:32,869 INFO    MainThread:31928 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 649
  total_bytes: 649
}

2022-01-19 15:52:33,074 INFO    MainThread:31928 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 649
  total_bytes: 649
}

2022-01-19 15:52:33,219 INFO    MainThread:31928 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 649
  total_bytes: 4407
}

2022-01-19 15:52:33,320 INFO    MainThread:31928 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 649
  total_bytes: 4433
}

2022-01-19 15:52:33,421 INFO    MainThread:31928 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 649
  total_bytes: 4433
}

2022-01-19 15:52:33,523 INFO    MainThread:31928 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1127
  total_bytes: 4433
}

2022-01-19 15:52:33,627 INFO    MainThread:31928 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4433
  total_bytes: 4433
}

2022-01-19 15:52:33,731 INFO    MainThread:31928 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4433
  total_bytes: 4433
}

2022-01-19 15:52:33,832 INFO    MainThread:31928 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4433
  total_bytes: 4433
}

2022-01-19 15:52:33,937 INFO    MainThread:31928 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4433
  total_bytes: 4433
}

2022-01-19 15:52:34,091 INFO    MainThread:31928 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4433
  total_bytes: 4433
}

2022-01-19 15:52:34,584 INFO    MainThread:31928 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4433
  total_bytes: 4433
}
local_info {
}

2022-01-19 15:52:35,739 INFO    MainThread:31928 [wandb_run.py:_append_files():2184] logging synced files
