2022-01-18 23:06:19,580 INFO    MainThread:7208 [wandb_setup.py:_flush():71] setting env: {}
2022-01-18 23:06:19,580 INFO    MainThread:7208 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-18 23:06:19,580 INFO    MainThread:7208 [wandb_init.py:_log_setup():371] Logging user logs to C:\Users\acb6595\Documents\Research\places2\project_portable\code\src\d01_pre_processing\wandb\run-20220118_230619-2aguzbhv\logs\debug.log
2022-01-18 23:06:19,580 INFO    MainThread:7208 [wandb_init.py:_log_setup():372] Logging internal logs to C:\Users\acb6595\Documents\Research\places2\project_portable\code\src\d01_pre_processing\wandb\run-20220118_230619-2aguzbhv\logs\debug-internal.log
2022-01-18 23:06:19,581 INFO    MainThread:7208 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002022B1D6610>
2022-01-18 23:06:19,590 INFO    MainThread:7208 [wandb_init.py:init():404] calling init triggers
2022-01-18 23:06:19,590 INFO    MainThread:7208 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-18 23:06:19,590 INFO    MainThread:7208 [wandb_init.py:init():449] starting backend
2022-01-18 23:06:19,591 INFO    MainThread:7208 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn, using: spawn
2022-01-18 23:06:19,595 INFO    MainThread:7208 [backend.py:ensure_launched():199] starting backend process...
2022-01-18 23:06:19,951 INFO    MainThread:7208 [backend.py:ensure_launched():204] started backend process with pid: 13232
2022-01-18 23:06:19,951 INFO    MainThread:7208 [wandb_init.py:init():458] backend started and connected
2022-01-18 23:06:19,956 INFO    MainThread:7208 [wandb_run.py:_label_probe_notebook():917] probe notebook
2022-01-18 23:06:19,957 INFO    MainThread:7208 [wandb_run.py:_label_probe_notebook():927] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-01-18 23:06:19,957 INFO    MainThread:7208 [wandb_init.py:init():519] updated telemetry
2022-01-18 23:06:19,965 INFO    MainThread:7208 [wandb_init.py:init():549] communicating current version
2022-01-18 23:06:21,445 INFO    MainThread:7208 [wandb_init.py:init():554] got version response upgrade_message: "wandb version 0.12.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-01-18 23:06:21,445 INFO    MainThread:7208 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2022-01-18 23:06:21,646 INFO    MainThread:7208 [wandb_init.py:init():592] starting run threads in backend
2022-01-18 23:06:22,579 INFO    MainThread:7208 [wandb_run.py:_console_start():1816] atexit reg
2022-01-18 23:06:22,580 INFO    MainThread:7208 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.WRAP
2022-01-18 23:06:22,580 INFO    MainThread:7208 [wandb_run.py:_redirect():1727] Wrapping output streams.
2022-01-18 23:06:22,581 INFO    MainThread:7208 [wandb_run.py:_redirect():1751] Redirects installed.
2022-01-18 23:06:22,581 INFO    MainThread:7208 [wandb_init.py:init():619] run started, returning control to user process
2022-01-18 23:06:26,142 INFO    MainThread:7208 [wandb_run.py:finish():1463] finishing run austinbergstrom/places_dry_run/2aguzbhv
2022-01-18 23:06:26,204 INFO    MainThread:7208 [jupyter.py:save_history():429] not saving jupyter history
2022-01-18 23:06:26,204 INFO    MainThread:7208 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-18 23:06:26,204 INFO    MainThread:7208 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-01-18 23:06:26,204 INFO    MainThread:7208 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2022-01-18 23:06:26,205 INFO    MainThread:7208 [wandb_run.py:_restore():1758] restore
2022-01-18 23:06:27,170 INFO    MainThread:7208 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 649
  total_bytes: 649
}

2022-01-18 23:06:27,732 INFO    MainThread:7208 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 649
  total_bytes: 649
}

2022-01-18 23:06:27,960 INFO    MainThread:7208 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 649
  total_bytes: 649
}

2022-01-18 23:06:28,666 INFO    MainThread:7208 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 649
  total_bytes: 4481
}

2022-01-18 23:06:28,768 INFO    MainThread:7208 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 649
  total_bytes: 4481
}

2022-01-18 23:06:28,872 INFO    MainThread:7208 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 649
  total_bytes: 4481
}

2022-01-18 23:06:28,973 INFO    MainThread:7208 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4314
  total_bytes: 4481
}

2022-01-18 23:06:29,075 INFO    MainThread:7208 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4481
  total_bytes: 4481
}

2022-01-18 23:06:29,177 INFO    MainThread:7208 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4481
  total_bytes: 4481
}

2022-01-18 23:06:29,279 INFO    MainThread:7208 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4481
  total_bytes: 4481
}

2022-01-18 23:06:29,380 INFO    MainThread:7208 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4481
  total_bytes: 4481
}

2022-01-18 23:06:29,694 INFO    MainThread:7208 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4481
  total_bytes: 4481
}

2022-01-18 23:06:30,140 INFO    MainThread:7208 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4481
  total_bytes: 4481
}
local_info {
}

2022-01-18 23:06:31,259 INFO    MainThread:7208 [wandb_run.py:_append_files():2184] logging synced files
