2021-12-27 16:57:22,048 INFO    MainThread:5196 [wandb_setup.py:_flush():71] setting env: {}
2021-12-27 16:57:22,048 INFO    MainThread:5196 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-27 16:57:22,048 INFO    MainThread:5196 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-27 16:57:22,048 INFO    MainThread:5196 [wandb_init.py:_log_setup():371] Logging user logs to C:\Users\acb6595\Documents\Research\places2\project_portable\code\src\d01_pre_processing\wandb\run-20211227_165722-ksyfe89q\logs\debug.log
2021-12-27 16:57:22,048 INFO    MainThread:5196 [wandb_init.py:_log_setup():372] Logging internal logs to C:\Users\acb6595\Documents\Research\places2\project_portable\code\src\d01_pre_processing\wandb\run-20211227_165722-ksyfe89q\logs\debug-internal.log
2021-12-27 16:57:22,057 INFO    MainThread:5196 [wandb_init.py:init():404] calling init triggers
2021-12-27 16:57:22,058 INFO    MainThread:5196 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2021-12-27 16:57:22,058 INFO    MainThread:5196 [wandb_init.py:init():449] starting backend
2021-12-27 16:57:22,058 INFO    MainThread:5196 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn, using: spawn
2021-12-27 16:57:22,062 INFO    MainThread:5196 [backend.py:ensure_launched():199] starting backend process...
2021-12-27 16:57:22,355 INFO    MainThread:5196 [backend.py:ensure_launched():204] started backend process with pid: 7092
2021-12-27 16:57:22,355 INFO    MainThread:5196 [wandb_init.py:init():458] backend started and connected
2021-12-27 16:57:22,356 INFO    MainThread:5196 [wandb_init.py:init():519] updated telemetry
2021-12-27 16:57:22,363 INFO    MainThread:5196 [wandb_init.py:init():549] communicating current version
2021-12-27 16:57:23,570 INFO    MainThread:5196 [wandb_init.py:init():554] got version response upgrade_message: "wandb version 0.12.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-12-27 16:57:23,570 INFO    MainThread:5196 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-12-27 16:57:23,783 INFO    MainThread:5196 [wandb_init.py:init():592] starting run threads in backend
2021-12-27 16:57:24,715 INFO    MainThread:5196 [wandb_run.py:_console_start():1816] atexit reg
2021-12-27 16:57:24,716 INFO    MainThread:5196 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.WRAP
2021-12-27 16:57:24,716 INFO    MainThread:5196 [wandb_run.py:_redirect():1727] Wrapping output streams.
2021-12-27 16:57:24,717 INFO    MainThread:5196 [wandb_run.py:_redirect():1751] Redirects installed.
2021-12-27 16:57:24,717 INFO    MainThread:5196 [wandb_init.py:init():619] run started, returning control to user process
2021-12-27 16:57:26,371 INFO    MainThread:5196 [wandb_run.py:finish():1463] finishing run austinbergstrom/places_dry_run/ksyfe89q
2021-12-27 16:57:26,371 INFO    MainThread:5196 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2021-12-27 16:57:26,371 INFO    MainThread:5196 [wandb_run.py:_restore():1758] restore
2021-12-27 16:57:27,224 INFO    MainThread:5196 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 647
  total_bytes: 647
}

2021-12-27 16:57:27,474 INFO    MainThread:5196 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 647
  total_bytes: 647
}

2021-12-27 16:57:27,795 INFO    MainThread:5196 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 647
  total_bytes: 4278
}

2021-12-27 16:57:27,904 INFO    MainThread:5196 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 647
  total_bytes: 4304
}

2021-12-27 16:57:28,009 INFO    MainThread:5196 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 647
  total_bytes: 4304
}

2021-12-27 16:57:28,110 INFO    MainThread:5196 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4304
  total_bytes: 4304
}

2021-12-27 16:57:28,212 INFO    MainThread:5196 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4304
  total_bytes: 4304
}

2021-12-27 16:57:28,318 INFO    MainThread:5196 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4304
  total_bytes: 4304
}

2021-12-27 16:57:28,421 INFO    MainThread:5196 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4304
  total_bytes: 4304
}

2021-12-27 16:57:28,522 INFO    MainThread:5196 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4304
  total_bytes: 4304
}

2021-12-27 16:57:28,726 INFO    MainThread:5196 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4304
  total_bytes: 4304
}

2021-12-27 16:57:29,206 INFO    MainThread:5196 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4304
  total_bytes: 4304
}
local_info {
}

2021-12-27 16:57:30,328 INFO    MainThread:5196 [wandb_run.py:_append_files():2184] logging synced files
