2021-12-23 12:56:55,777 INFO    MainThread:25108 [wandb_setup.py:_flush():71] setting env: {}
2021-12-23 12:56:55,777 INFO    MainThread:25108 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-23 12:56:55,778 INFO    MainThread:25108 [wandb_init.py:_log_setup():371] Logging user logs to C:\Users\acb6595\Documents\Research\places2\project_portable\code\src\d01_pre_processing\wandb\run-20211223_125655-2bv6zawk\logs\debug.log
2021-12-23 12:56:55,778 INFO    MainThread:25108 [wandb_init.py:_log_setup():372] Logging internal logs to C:\Users\acb6595\Documents\Research\places2\project_portable\code\src\d01_pre_processing\wandb\run-20211223_125655-2bv6zawk\logs\debug-internal.log
2021-12-23 12:56:55,778 INFO    MainThread:25108 [wandb_init.py:init():404] calling init triggers
2021-12-23 12:56:55,778 INFO    MainThread:25108 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2021-12-23 12:56:55,778 INFO    MainThread:25108 [wandb_init.py:init():449] starting backend
2021-12-23 12:56:55,778 INFO    MainThread:25108 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn, using: spawn
2021-12-23 12:56:55,785 INFO    MainThread:25108 [backend.py:ensure_launched():199] starting backend process...
2021-12-23 12:56:56,093 INFO    MainThread:25108 [backend.py:ensure_launched():204] started backend process with pid: 26200
2021-12-23 12:56:56,094 INFO    MainThread:25108 [wandb_init.py:init():458] backend started and connected
2021-12-23 12:56:56,094 INFO    MainThread:25108 [wandb_init.py:init():519] updated telemetry
2021-12-23 12:56:56,097 INFO    MainThread:25108 [wandb_init.py:init():549] communicating current version
2021-12-23 12:56:57,631 INFO    MainThread:25108 [wandb_init.py:init():554] got version response upgrade_message: "wandb version 0.12.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-12-23 12:56:57,631 INFO    MainThread:25108 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-12-23 12:56:58,031 WARNING MainThread:25108 [wandb_init.py:init():938] interrupted
Traceback (most recent call last):
  File "C:\Users\acb6595\Anaconda3\envs\research_portable\lib\site-packages\wandb\sdk\wandb_init.py", line 917, in init
    run = wi.init()
  File "C:\Users\acb6595\Anaconda3\envs\research_portable\lib\site-packages\wandb\sdk\wandb_init.py", line 565, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "C:\Users\acb6595\Anaconda3\envs\research_portable\lib\site-packages\wandb\sdk\interface\interface.py", line 205, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "C:\Users\acb6595\Anaconda3\envs\research_portable\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 334, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "C:\Users\acb6595\Anaconda3\envs\research_portable\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 232, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\acb6595\Anaconda3\envs\research_portable\lib\site-packages\wandb\sdk\interface\router.py", line 32, in get
    is_set = self._object_ready.wait(timeout)
  File "C:\Users\acb6595\Anaconda3\envs\research_portable\lib\threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\acb6595\Anaconda3\envs\research_portable\lib\threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
