2021-12-27 16:56:04,085 INFO    MainThread:25964 [wandb_setup.py:_flush():71] setting env: {}
2021-12-27 16:56:04,085 INFO    MainThread:25964 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-27 16:56:04,085 INFO    MainThread:25964 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-27 16:56:04,086 INFO    MainThread:25964 [wandb_init.py:_log_setup():371] Logging user logs to C:\Users\acb6595\Documents\Research\places2\project_portable\code\src\d01_pre_processing\wandb\run-20211227_165604-37uuwg5y\logs\debug.log
2021-12-27 16:56:04,086 INFO    MainThread:25964 [wandb_init.py:_log_setup():372] Logging internal logs to C:\Users\acb6595\Documents\Research\places2\project_portable\code\src\d01_pre_processing\wandb\run-20211227_165604-37uuwg5y\logs\debug-internal.log
2021-12-27 16:56:04,096 INFO    MainThread:25964 [wandb_init.py:init():404] calling init triggers
2021-12-27 16:56:04,096 INFO    MainThread:25964 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2021-12-27 16:56:04,096 INFO    MainThread:25964 [wandb_init.py:init():449] starting backend
2021-12-27 16:56:04,096 INFO    MainThread:25964 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn, using: spawn
2021-12-27 16:56:04,105 INFO    MainThread:25964 [backend.py:ensure_launched():199] starting backend process...
2021-12-27 16:56:05,429 INFO    MainThread:25964 [backend.py:ensure_launched():204] started backend process with pid: 9860
2021-12-27 16:56:05,430 INFO    MainThread:25964 [wandb_init.py:init():458] backend started and connected
2021-12-27 16:56:05,431 INFO    MainThread:25964 [wandb_init.py:init():519] updated telemetry
2021-12-27 16:56:05,455 INFO    MainThread:25964 [wandb_init.py:init():549] communicating current version
2021-12-27 16:56:06,504 INFO    MainThread:25964 [wandb_init.py:init():554] got version response upgrade_message: "wandb version 0.12.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-12-27 16:56:06,505 INFO    MainThread:25964 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-12-27 16:56:06,784 INFO    MainThread:25964 [wandb_init.py:init():592] starting run threads in backend
2021-12-27 16:56:07,754 INFO    MainThread:25964 [wandb_run.py:_console_start():1816] atexit reg
2021-12-27 16:56:07,754 INFO    MainThread:25964 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.WRAP
2021-12-27 16:56:07,755 INFO    MainThread:25964 [wandb_run.py:_redirect():1727] Wrapping output streams.
2021-12-27 16:56:07,757 INFO    MainThread:25964 [wandb_run.py:_redirect():1751] Redirects installed.
2021-12-27 16:56:07,758 INFO    MainThread:25964 [wandb_init.py:init():619] run started, returning control to user process
2021-12-27 16:56:37,039 INFO    MainThread:25964 [wandb_run.py:finish():1463] finishing run austinbergstrom/places_dry_run/37uuwg5y
2021-12-27 16:56:37,040 INFO    MainThread:25964 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2021-12-27 16:56:37,040 INFO    MainThread:25964 [wandb_run.py:_restore():1758] restore
2021-12-27 16:56:37,819 INFO    MainThread:25964 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 647
  total_bytes: 647
}

2021-12-27 16:56:38,444 INFO    MainThread:25964 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 647
  total_bytes: 647
}

2021-12-27 16:56:38,662 INFO    MainThread:25964 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 647
  total_bytes: 647
}

2021-12-27 16:56:38,868 INFO    MainThread:25964 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 647
  total_bytes: 4640
}

2021-12-27 16:56:38,971 INFO    MainThread:25964 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 647
  total_bytes: 4667
}

2021-12-27 16:56:39,089 INFO    MainThread:25964 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 647
  total_bytes: 4667
}

2021-12-27 16:56:39,193 INFO    MainThread:25964 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3881
  total_bytes: 4667
}

2021-12-27 16:56:39,303 INFO    MainThread:25964 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4667
  total_bytes: 4667
}

2021-12-27 16:56:39,406 INFO    MainThread:25964 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4667
  total_bytes: 4667
}

2021-12-27 16:56:39,508 INFO    MainThread:25964 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4667
  total_bytes: 4667
}

2021-12-27 16:56:39,618 INFO    MainThread:25964 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4667
  total_bytes: 4667
}

2021-12-27 16:56:39,942 INFO    MainThread:25964 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4667
  total_bytes: 4667
}

2021-12-27 16:56:40,474 INFO    MainThread:25964 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4667
  total_bytes: 4667
}
local_info {
}

2021-12-27 16:56:42,053 INFO    MainThread:25964 [wandb_run.py:_append_files():2184] logging synced files
